# Demonstrate how to calculate the feature recalibration

In [1]:
batch, channel, depth, height, width = [1, 2, 3, 4, 5]


import numpy as np
import torch

num_array = np.array([num for num in range(1, batch * channel * depth * height * width + 1)]).reshape([batch, channel, depth, height, width])

input_tensor = torch.from_numpy(num_array)
Feat = input_tensor

/home/frederique_hsu/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
Depth = depth
Height = height
Width = width
Channel = channel

#              b  c  d  h  w
cuboid0 = Feat[0, 0, :, :, :]
cuboid1 = Feat[0, 1, :, :, :]

#                    b  c  d  h  w
channel_feats = Feat[0, :, :, :, :]
Am = channel_feats

# print(Am)

In [8]:
Depth_axis = Feat.permute(0, 2, 1, 3, 4)
print("Depth_axis.shape =", Depth_axis.shape)

Height_axis = Feat.permute(0, 3, 2, 1, 4)
print("Height_axis.shape = ", Height_axis.shape)

Depth_axis.shape = torch.Size([1, 3, 2, 4, 5])
Height_axis.shape =  torch.Size([1, 4, 3, 2, 5])


计算
$$
    \int_{V} A_m d(Depth) = \sum_{h=1}^{H_m} \sum_{w=1}^{W_m} A_m[:, :, h, w]
$$

$$
    \int_{V} A_m d(Height) = \sum_{d=1}^{D_m} \sum_{w=1}^{W_m} A_m[:, d, :, w]
$$

$$
    \int_{V} A_m d(Width) = \sum_{d=1}^{D_m} \sum_{h}^{H_m} A_m[:, d, h, :]
$$

In [4]:
#                    2         3     4       5
Results = np.zeros([Channel, Depth, Height, Width])

for h in range(0, Height):
    for w in range(0, Width):
        intermediate_result = Am[:, :, h, w]
        print(intermediate_result)
    print("\n")

tensor([[  1,  21,  41],
        [ 61,  81, 101]])
tensor([[  2,  22,  42],
        [ 62,  82, 102]])
tensor([[  3,  23,  43],
        [ 63,  83, 103]])
tensor([[  4,  24,  44],
        [ 64,  84, 104]])
tensor([[  5,  25,  45],
        [ 65,  85, 105]])


tensor([[  6,  26,  46],
        [ 66,  86, 106]])
tensor([[  7,  27,  47],
        [ 67,  87, 107]])
tensor([[  8,  28,  48],
        [ 68,  88, 108]])
tensor([[  9,  29,  49],
        [ 69,  89, 109]])
tensor([[ 10,  30,  50],
        [ 70,  90, 110]])


tensor([[ 11,  31,  51],
        [ 71,  91, 111]])
tensor([[ 12,  32,  52],
        [ 72,  92, 112]])
tensor([[ 13,  33,  53],
        [ 73,  93, 113]])
tensor([[ 14,  34,  54],
        [ 74,  94, 114]])
tensor([[ 15,  35,  55],
        [ 75,  95, 115]])


tensor([[ 16,  36,  56],
        [ 76,  96, 116]])
tensor([[ 17,  37,  57],
        [ 77,  97, 117]])
tensor([[ 18,  38,  58],
        [ 78,  98, 118]])
tensor([[ 19,  39,  59],
        [ 79,  99, 119]])
tensor([[ 20,  40,  60],


In [14]:
import torch
import numpy as np

cube_npy = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

cube_tensor = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])

print(cube_npy.shape)
print(cube_tensor.shape)

(2, 3, 4)
torch.Size([3, 2, 3])


In [20]:
depth_integration_npy = np.load("D_Integration.npy")
height_integration_npy = np.load("H_Integration.npy")
width_integration_npy = np.load("W_Integration.npy")

print(depth_integration_npy.shape, 
      height_integration_npy.shape, 
      width_integration_npy.shape)

total = depth_integration_npy + height_integration_npy + width_integration_npy
print(total.shape)

(1, 16, 80, 1, 1) (1, 16, 1, 192, 1) (1, 16, 1, 1, 304)
(1, 16, 80, 192, 304)


# 计算指标平均值

In [5]:
FPR_list = [
0.006,
0.031,

0.023,
0.046,
0.031,
0.035,
0.034,
0.023,
0.027,
0.055,
0.024,
0.03 ,
0.042,
0.084,
0.043,
0.034,



0.036,
0.039,
0.017,
0.018,
0.046,

0.014,
0.016]

FNR_list = [
7.119,
7.676,

3.712,
4.59 ,
4.924,
4.141,
5.475,
3.4  ,
4.291,
3.997,
5.497,
4.487,
4.036,
3.823,
3.584,
4.417,



0.401,
0.288,
0.984,
2.352,
1.354,

3.294,
2.107,
]

Sensitivity_list = [
92.88,
92.32,

96.29,
95.41,
95.08,
95.86,
94.53,
96.6 ,
95.71,
96.00,
94.5 ,
95.51,
95.96,
96.18,
96.42,
95.58,



99.6 ,
99.39,
99.02,
97.65,
98.65,

96.71,
97.89,
]

Precision_list = [
98.18,
91.01,

96.00,
87.19,
92.47,
91.31,
91.42,
93.67,
92.16,
86.13,
93.15,
92.27,
89.15,
79.61,
87.12,
92.17,



84.2 ,
82.94,
94.59,
93.35,
87.13,

95.3 ,
94.49,
]

DSC_list = [
95.04,
91.66,

96.06,
90.65,
93.76,
93.24,
92.94,
94.96,
93.62,
90.8 ,
93.76,
93.86,
92.43,
87.11,
91.53,
93.85,



91.26,
90.42,
96.57,
95.33,
92.45,

96.26,
95.36,
]

BD_list = [
66.84,
84.18,

88.44,
79.27,
70.28,
80.72,
74.57,
83.76,
79.23,
82.23,
77.36,
76.57,
75.53,
70.35,
78.66,
78.39,



100  ,
100  ,
97.24,
96.89,
96   ,

91.16,
91.77,
]

TLD_list = [
82.96,
92.28,

93.92,
88.92,
82.27,
88.63,
85.34,
90.9 ,
88.00,
89.15,
86.64,
88.32,
87.34,
87.09,
89.93,
90.1 ,



99.89,
99.9 ,
96.57,
96   ,
95.64,

95.2 ,
95.32]

In [6]:
FPR_avg = np.mean(np.array(FPR_list).astype(np.float64))
FNR_avg = np.mean(np.array(FNR_list).astype(np.float64))
Sensitivity_avg = np.mean(np.array(Sensitivity_list).astype(np.float64))
Precision_avg = np.mean(np.array(Precision_list).astype(np.float64))
DSC_avg = np.mean(np.array(DSC_list).astype(np.float64))
BD_avg = np.mean(np.array(BD_list).astype(np.float64))
TLD_avg = np.mean(np.array(TLD_list).astype(np.float64))

print(FPR_avg, FNR_avg, Sensitivity_avg, Precision_avg, DSC_avg, BD_avg, TLD_avg)

0.032782608695652186 3.73691304347826 96.2495652173913 90.65260869565218 93.1704347826087 83.45391304347827 90.88304347826089
